[package]
name = "neonex-shared"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"], default-features = false }
bevy = { version = "0.16.1", default-features = false }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
